name: Analysis
on: [push]

jobs:
  build:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: PHP CodeSniffer
        run: |
          composer global require "divante-ltd/pimcore-coding-standards":"^0.1" \
            --no-interaction --prefer-dist --ignore-platform-reqs --quiet
          /home/runner/.composer/vendor/bin/phpcs --config-set colors 1
          /home/runner/.composer/vendor/bin/phpcs \
            --extensions=php \
            --standard=/home/runner/.composer/vendor/divante-ltd/pimcore-coding-standards/Standards/Pimcore5/ruleset.xml \
            ./src  -s

      - name: PHP Mess Detector
        run: |
          composer global require "phpmd/phpmd":"^2.6" \
            --no-interaction --prefer-dist --ignore-platform-reqs --quiet
          /home/runner/.composer/vendor/bin/phpmd src text \
            /home/runner/.composer/vendor/divante-ltd/pimcore-coding-standards/Standards/Pimcore5/rulesetmd.xml

      - name: PHP Copy/Paste Detector
        run: |
          composer global require "sebastian/phpcpd":"^4.1" \
            --no-interaction --prefer-dist --ignore-platform-reqs --quiet
          /home/runner/.composer/vendor/bin/phpcpd src

      - name: PHP DocBlock Checker
        run: |
          composer global require "block8/php-docblock-checker":"^1.10" \
            --no-interaction --prefer-dist --ignore-platform-reqs --quiet
          /home/runner/.composer/vendor/bin/phpdoccheck --directory=src
